#!/usr/bin/env bash
#
# Generate deploy/.env with random credentials.
#
# The compose file declares its secrets as ${VAR:?...}, so the stack refuses to
# start until this has run. That is deliberate: the previous ${VAR:-default}
# form meant a deployment that forgot to set anything came up anyway, with
# credentials published in this repository.
#
# Existing values are preserved. That matters for DOCSERVER_JWT_SECRET in
# particular — Nextcloud and Document Server must agree on it, so regenerating
# it on an existing deployment breaks co-editing until both are reconfigured.
#
# Usage: scripts/gen_env.sh [--force] [--print]

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/deploy/.env"
FORCE=0
PRINT=0
for a in "$@"; do
  case "$a" in
    --force) FORCE=1 ;;
    --print) PRINT=1 ;;
    *) echo "unknown option: $a" >&2; exit 2 ;;
  esac
done

secret() { openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'; }

# Read a value already present in the file, so re-running is safe.
existing() {
  [ -f "$ENV_FILE" ] || return 0
  sed -n "s/^$1=//p" "$ENV_FILE" | head -1
}

declare -A VALUES
for key in DB_ROOT_PASSWORD DB_PASSWORD NEXTCLOUD_ADMIN_PASSWORD DOCSERVER_JWT_SECRET; do
  cur="$(existing "$key")"
  if [ -n "$cur" ] && [ "$FORCE" -eq 0 ]; then
    VALUES[$key]="$cur"
  else
    VALUES[$key]="$(secret)"
  fi
done

ADMIN_USER="$(existing NEXTCLOUD_ADMIN_USER)"; ADMIN_USER="${ADMIN_USER:-lightadmin}"
PUBLIC_HOST="$(existing LIGHTOFFICE_PUBLIC_HOST)"; PUBLIC_HOST="${PUBLIC_HOST:-10.0.7.10}"

mkdir -p "$(dirname "$ENV_FILE")"
umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/gen_env.sh — do not commit.
# Regenerating DOCSERVER_JWT_SECRET on a live deployment breaks co-editing
# until Nextcloud's onlyoffice app is reconfigured with the new value.
DB_ROOT_PASSWORD=${VALUES[DB_ROOT_PASSWORD]}
DB_PASSWORD=${VALUES[DB_PASSWORD]}
NEXTCLOUD_ADMIN_USER=$ADMIN_USER
NEXTCLOUD_ADMIN_PASSWORD=${VALUES[NEXTCLOUD_ADMIN_PASSWORD]}
DOCSERVER_JWT_SECRET=${VALUES[DOCSERVER_JWT_SECRET]}
LIGHTOFFICE_PUBLIC_HOST=$PUBLIC_HOST
EOF
chmod 600 "$ENV_FILE"

echo "wrote $ENV_FILE (mode 600)"
if [ "$PRINT" -eq 1 ]; then
  cat "$ENV_FILE"
else
  echo "admin user: $ADMIN_USER   public host: $PUBLIC_HOST"
  echo "secrets withheld; use --print to show them"
fi
